### ISSUE TITLE
Исправить обычные коллайдеры на двумерные (Collider2d) в SampleScene

### ISSUE THREAD

**Issue by popuz** [DanilaTumanov/GB-project#33]
Поскольку мы будем пользоваться встроенной двумерной физикой, то везде ставим двумерные коллайдеры (и rigidbody)

![default](https://user-images.githubusercontent.com/35366872/41244220-13721934-6dad-11e8-80b2-3fe4fc131297.PNG)

**Comment by stratok** [comment]
Ох ребятки, косякнул, по привычке нафиначил.) Сейчас поправлю.
